### ISSUE TITLE
Using NAACCR

### ISSUE THREAD

**Issue by MaximMoinat** [thehyve/ohdsi-etl-prias#33]
I see we use some mappings to NAACCR concepts, e.g. [35917476](https://athena.ohdsi.org/search-terms/terms/35917476). This vocabulary is not by default included in a download from Athena (needs to be selected manually). 

Is the use of NAACCR vocabularies documented somewhere? (both here and in the ohdsi-omop-pioneer repo).

**Comment by Spayralbe** [comment]
The NAACR vocabulary has been made available on the central server.
