### ISSUE TITLE
Update ETL to standardized oncology vocabulary

### ISSUE THREAD

**Issue by sremmers** [thehyve/ohdsi-etl-prias#41]
old mapping:
https://github.com/thehyve/ohdsi-etl-prias/blob/4599f9227ce802e7c9ff41fa796da2a3fbc2c2d5/resources/mapping_tables/variable_mapping.csv

For example, Gleason score is nowadays standardized as https://athena.ohdsi.org/search-terms/terms/1634459

**Comment by Spayralbe** [comment]
Closed by #42
